version: 2
updates:
  - package-ecosystem: "gomod" # Check for Go updates
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker" # Check for Docker base image updates
    directory: "/"
    schedule:
      interval: "weekly"